### ISSUE TITLE
Axes mixed up?

### ISSUE THREAD

**Issue by mortenfyhn** [ros-visualization/rqt_pose_view#2]
I just tested pose view with a sequence of simple rotations, and the box in the visualization appears to rotate the correct amount around the correct axis, but in the wrong direction.

These are the rotations I tried and the results I got:

| roll | pitch | yaw  |  q.x |  q.y |  q.z |  q.w | result     | expectation |
|------|-------|------|------|------|------|------|------------|-------------|
| 15°  | 0     | 0    | .13  | 0    | 0    | .99  | neg. roll  | pos. roll   |
| 0    | 15°   | 0    | 0    | .13  | 0    | .99  | neg. pitch | pos. pitch  |
| 0    | 0     | 15°  | 0    | 0    | .13  | .99  | neg. yaw   | pos. yaw    |
| -15° | 0     | 0    | -.13 | 0    | 0    | .99  | pos. roll  | neg. roll   |
| 0    | -15°  | 0    | 0    | -.13 | 0    | .99  | pos. pitch | neg. pitch  |
| 0    | 0     | -15° | 0    | 0    | -.13 | .99  | pos. yaw   | neg. yaw    |

I'm assuming that the colors in pose view are (red = x), (green = y), (blue = z), and that it uses right-handed rotations. Is that correct?

(I used http://www.andre-gaschler.com/rotationconverter/ to calculate quaternions to test based on roll/pitch/yaw values. Since the rotations are simple, Euler angle convention should not matter, but I had it set to ZYX.)

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. `tf` returns the matrix in row-major while `OpenGL` expects column-major. Please see #3 for the fix.

**Comment by mortenfyhn** [comment]
Wonderful! I can confirm that your fix seems to work.

**Comment by dirk-thomas** [comment]
Thank you for trying the patch and reporting back. The fix is available in the newly released version 0.5.8.
