### ISSUE TITLE
Parameter for topic to subscribe to

### ISSUE THREAD

**Issue by mortenfyhn** [ros-visualization/rqt_pose_view#4]
Hi, I think it would be useful to have an optional node parameter for which topic the node should listen to for Imu messages. Then it will be possible to put pose view in a launch script without having to do the topic drag-and-drop manually while running. Thoughts?

**Comment by dirk-thomas** [comment]
Sounds like a useful addition. Please provide a pull request implementing a command line option for it.

**Comment by mortenfyhn** [comment]
Nice. Do you consider it necessary to add this as a command line option? My initial idea was simply a parameter server entry (private to the rqt_pose_view node) that the node attempts to read. If the parameter exists, the node attempts to subscribe to it. Otherwise, it ignores it and behaves as before.

I have a rough implementation of this, but I haven't done any command line argument-related changes yet.

**Comment by dirk-thomas** [comment]
It depends how you want to use the plugin. When used stand alone the command line options makes more sense imo. When being used together with other platforms a parameter is fine - it is just not very discoverable to users.

**Comment by mortenfyhn** [comment]
My use case right now just requires the parameter, so I'll start off by cleaning up and PR-ing that, and leave the command line option for some day in the future.
